language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer require phpspec/phpspec:~2.0
    - travis_retry composer install --dev --prefer-dist --no-interaction --no-progress --no-plugins

script:
    - php vendor/bin/phpspec run -fpretty
